apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 454042841093.dkr.ecr.ap-south-1.amazonaws.com/ecr-eks:latest
          ports:
            - containerPort: 80
